### ISSUE TITLE
Function calls to previous versions need to be forwarded

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#1]
Although component's prototype is overriden after an update, there may still exist references to old versions of methods. Consider this example:

``` javascript
  getInitialState: function () {
    return {
      message: 'Hi'
    };
  },

  componentDidMount: function () {
    window.setInterval(this.tick, 1000);
  },

  tick: function () {
    this.setState({
      message: 'I am Batman'
    });
  },

  render: function () {
    return <div>{this.state.message}</div>;
  }
```

If I edit the message inside `tick` to say `I am Robin`, it will not change because `setInterval` was called with the old version of the method. Overwriting prototype doesn't help because `tick` was already accessed and a reference to it is stored somewhere else.

To solve this problem, we need to reimplement `createHotClass` which, instead of adding a mixin, should return a proxy instance that forwards method calls to the freshest component prototype.

**Comment by IAkumaI** [comment]
Same bug was found. Look at this code:

```
componentDidMount() {
        this.interval = setInterval(this.updateAll, this.props.updateInterval);
        this.updateAll();
    }

    componentWillUnmount() {
        !!this.interval && clearInterval(this.interval);
    }

    updateAll() {
        Qajax('/api/somemethod')
            .then(Qajax.filterSuccess)
            .then(Qajax.toJSON)
            .then((response) => {
                this.setState({....}); // Will not work after hot-reload if babel use es2015 preset
            });
    }
```

Do you know why? Because `this` will transpile to local `_this` (or the same) because of `() => {}` function. Function must save context, babel transpile it to do this in old browsers....well, I think you understand (my english is bad, i dont know how to white it better).

And, very bad side of this bug: No errors on page, no errors in console, no error anywhere. About 30 mins I tried to understand why code "just not work" :)

Maybe it can be fixed too? ))
