### ISSUE TITLE
Steal good ideas from LiveReactload

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#111]
I haven't taken a close look yet, but the new [LiveReactload](https://github.com/milankinen/livereactload) for Browserify does a few things I really like:

* Explains what works and what doesn't in the docs;
* Contains examples showcasing corner cases.

@milankinen I'd love to hear your thoughts if you found better solutions to any other problems.
I'm excited to work together on making live reloading a mundane reality. :+1:

**Comment by milankinen** [comment]
+1 to this issue :+1: 

When someone starts to use devtool like this without the understanding of its limitations, he/she probably ends up writing code that prevents the tool working right => tool´s fault => go to the forums telling that "tools is not working". IMO, that's why listing the known limitations is crucial for maintaining a "good publicity".

Sorry, I didn't fully understand your comment: what are are the other problems? Actually I was positively surprised how well the React Hot API worked. 

Only problematic case was to maintain the original `react` package over reloading events (when bundle reloads, it contains new `react` as well, which does not known about the existing classes or mounted root instances) so I decided to override the original `require` function at the beginning of the module. This function caches the first instance to the `window` and serves it when the next bundle components require React.

I'm also worried about the following issues:

* **Memory consumption with big bundles**? How well can JavaScript engines manage the GC when many big bundles have been thrown to the trash bin after multiple reloading events.
* **Module renaming**? Might there be conflicts when same module gets renamed or moved (since Hot API uses filename as an identifier)
* **Non-forward compatible state**? Well.. this is obvious: if your reloaded application assumes that your state has a schema that is not compatible with the current one, then you just have to reset the state (reload page). But could this be avoided somehow? 


What kind of challenges have you encountered? This is a great honor to me and I´m also excited about this co-operation.

**Comment by gaearon** [comment]
My biggest problem was always lack of tests. I'm solving that with [React Hotify](https://github.com/gaearon/react-hotify), the successor to React Hot API. It has not reached feature parity yet but it's fully [covered with tests](https://github.com/gaearon/react-hotify/blob/master/src/__tests__/makeHotify-test.js).

Another issue is the complication of passing root React instances to the React Hot API. I did it so React Hot API could walk mounted instance tree and force deep updates. In [React Hotify](https://github.com/gaearon/react-hotify), I don't do that anymore, instead [monkey-patching `componentWillMount` and `componentWillUnmount`](https://github.com/gaearon/react-hotify/blob/master/src/makeHotify.js#L20-L40) to track instance list for every component.

Yet another issue is the complicated API of React Hot API. In [React Hotify](https://github.com/gaearon/react-hotify), I'm [exporting a decorator instead](https://github.com/gaearon/react-hotify#webpack-without-babel-plugin) and letting consumer use [a Babel plugin](https://github.com/gaearon/babel-plugin-react-hotify) to put it automatically in the source code. **The nice thing about this approach is that both parts are fully reusable in Browserify environment.** Both React Hotify and the Babel plugin don't depend on Webpack at all.

The tricky part in Browserify is **reloading only the changed module**. In Webpack, we have HMR for this, and it's the last missing piece. Please correct me if I'm wrong, but I think you are reloading the whole application code in LiveReactload? This is the reasons shims break, you need to do `require` trickery, etc. This seems fragile.

I know @Kureev wanted to look into using the new [React Hotify](https://github.com/gaearon/react-hotify) with Browserify. I wonder if you have any thoughts about compiling a “partial update” for Browserify so it only re-executes the code of our component annotated with `@hotify` calls with Babel.
