### ISSUE TITLE
Server-side use and webpack

### ISSUE THREAD

**Issue by skevy** [gaearon/react-hot-loader#113]
Lately I've been playing around with hot module reloading with webpack on the backend. Seemed like it would be pretty neat to hot-load in my React component changes without restarting the server. :)

I threw in react-hot-loader to my backend webpack config. At first glance, it seems to work...and it's awesome!

But, on the first hot load of a React component, hot loader throws this warning:

```
It appears that React Hot Loader isn't configured correctly. If you're using NPM, make sure your dependencies don't drag duplicate React distributions into their node_modules and that require("react") corresponds to the React instance you render your app with. If you're u
sing a precompiled version of React, see https://github.com/gaearon/react-hot-loader/tree/master/docs#usage-with-external-react for integration instructions.
```

Of course, this makes perfect sense: the reason RHL even throws this error is if ReactMount has no active instances in it, which it wouldn't when just doing React.renderToString() in an express route, for example.

This error goes away after the first hot load, however (which I believe is because somewhere down the line, when RHL does its forceUpdating and all of that, components get registered in the ReactMount singleton).

Now, I'm no expert with React Hot Loader or ReactMount, but in my small amount of investigation, it seems like if React-Hot-Loader is being used for backend hot loading purposes, features like running ```forceUpdate``` on all the components could be turned off, and all we'd really need to do is update the prototype. We could also get rid of this warning when running server-side

I'm wondering if the best way to go about doing something like this is simply setting a "server" flag in react-hot-api and turning off the proper things, or doing something different all together?

I'm curious to hear thoughts on this. Getting this working smoothly would be really powerful, as one of the crappy parts of building an isomorphic app is getting all the great benefits of react-hot-loader on the front-end but still dealing with the "restart the server on every change" behavior on back-end.

**Comment by jlongster** [comment]
Personally I think what's more interesting for the backend is more general patching of modules, like replacing all top-level functions. The backend tends to have a bunch of code outside of React components. Also, can't you just render everything client-side while developing, or is something I'm missing?

I'm actually *really* close to my last blog post in the backend webpack series which shows how to hot-patch backend servers (generally speaking, not using react-hot-loader, but using the same approach).

**Comment by skevy** [comment]
Regarding rendering client-side while developing - yes, of course, but I just found that restarting my server (there are a few connections it's making to different db's that can cause the server restart to lag a bit) was much slower than the sub-second times HMR provided. So if I'm coding a component and I'm testing a piece of functionality that is closely related to the server-side render, I have to continuously refresh the page, which of course negates the *client-side* benefits of HMR and RHL, which is exactly why it would be awesome to have server-side.

Re: doing more general patching of modules...perhaps that really is all that's needed here. If we don't have to worry about some of the other things RHL is doing (such as forceUpdating changed components) on the server, then yah, we can probably just do something more general.

Though, I feel like there could still be benefits to having more specific HMR loaders (such as RHL) server-side, but admittedly I don't have a specific use-case at the moment.  I worry a little bit about writing a plugin to HMR that just does things super general, but perhaps I'm just jaded from the front-end. On FE you have lots of persistent state to keep (which is why HMR is so important)...on the backend, there is presumably less persistent state, thus you don't have to be as careful with how you replace things. In addition, I was having trouble getting HMR to work with express without just closing the server and restarting it (which kind of defeats the purpose), but perhaps I was just doing something wrong.

I'll give it some more thought though, and of course read your post when it's published. :+1:

**Comment by jlongster** [comment]
I find webpack's HMR infrastructure a bit unintuitive, to be honest. What I really want (coming from a Lisp background) is to literally replace a function or class in place. Webpack's HMR encourages reloading not only the entire module, but all the modules up the dependency chain. It has to do this because if a module is reloaded, anything that depends on it must be reloaded as well to see the changes. This works best when the root module is the only one with side effects, like starting a server.

That's what you ran into. You needed to stop the server in a `dispose` handler, right? That way the new root module could start a new one. Another way you could handle it would be to pass the server instance along:

```js
var server;

if(module.hot) {
  if(!module.hot.data) {
    // no data means this is the first time this module is run
    server = new Server();
    server.listen();
  }
  else {
    server = module.hot.data.server;
  }

  module.hot.dispose(function(data) {
    data.server = server;
  });
})
```

I most likely made some mistakes in the above... but like I said, not intuitive at all.

My post shows a technique similar to react-hot-loader, but instead of patching existing react instances, it patches all the top-level functions in a module. Yeah, these kinds of things get hairy, and I'm usually hesitant about them too. But it turns out that if you restrict the heuristics to make it *extremely* simple, it's really straight-forward. If you define a top-level function `foo` in module A, start the server, change `foo` and save the file, my loader will take the source of the new `foo`, eval it inside module A to create a function instance, and set `foo` to it points to the new instance. This *only* happens with top-level functions defined like `function foo() { ... }`. No way we can hot patch closures or all that without touching the engine debugger. Just doing top-level functions, this patching should never change semantics and is always created inside the exact same scope.

We can probably improve the heuristics to patch a few more things, but I'm starting stupidly simple to prove that it can be done consistently without breaking things.

What will be interesting for React components is patching classes. No reason we could not do the exact same things for classes: use eval to create a function in the same scope, and simply set it on the prototype (`MyClass.prototype.foo = newFoo`). If that works, it will probably solve your use case.

However, `react-hot-loader` definitely is the well-trodden path so it might make sense to get server-side support in it as well.

I'm still a little confused as to what code is running server-side inside a React component that *can't* be run client-side? Usually with isomorphic apps you can disalbe server-side rendering and everything just happens on the client, but you must have server-specific code in your components. I'm curious what code that is.

**Comment by skevy** [comment]
The specific use case was bootstrapping components. I was testing server-side flux functionality, so I needed to not disable server-side rendering. I understand that it's kind of a contrived use-case and not one that everyone runs into all the time, but I think there are definite cases where it's useful.

**Comment by jlongster** [comment]
It totally makes sense! I haven't done a really complicated server-side app, so I was merely curious to learn what people are putting into components.

I'm in my blog-writing mode, sorry if I dumped too much here. I think we need a companion to react-hot-loader on the server, whether or not it's baked into react-hot-loader or not.

**Comment by skevy** [comment]
Totally agree. We'll sync back on this after @gaearon weighs in and we all get a chance to read your blog post. :)

**Comment by gaearon** [comment]
Hey! A few thoughts:

* I'm not doing server rendering so I can't really weigh on this as I'm not familiar with the workflow;
* I'd rather avoid complicating RHL and I'm happy to see alternatives (from which RHL might steal someday);
* I've been thinking about making RHL more generic... In particular I'd be happy to split [react-hot-api](https://github.com/gaearon/react-hot-api) into a generic “prototype patcher” and React-specific tree traverser that calls `forceUpdate`.

What do you guys suggest?

**Comment by jlongster** [comment]
There's potential in #3, in that I could take your prototype patcher and use it with my hot loader, and that might make server-side stuff work well. I don't really know yet though. If you'd rather avoid complicating RHL, I say we try that first and see what we can get out of it.

I'm happy to try to extract out the prototype patching myself and see if it's worth doing, unless you want to abstract it out regardless.

**Comment by gaearon** [comment]
>I'm happy to try to extract out the prototype patching myself and see if it's worth doing, unless you want to abstract it out regardless.

Please do! I'm busy with other projects at the moment and plan to take another look at RHL in a month or so.

**Comment by skevy** [comment]
Just read your post @jlongster. Great read.

I love monkey-hot-loader. Smart stuff.

I still feel like there's use to having react-hot-loader work on the server, in order to work with the workflow you described in your post and building isomorphic apps. As I said, I think we really just need to turn off the forceUpdating (because it's not necessary) when on the server. Though, I totally agree with @gaearon's point of not complicated RHL, so I'm not sure of the proper route to go here...

**Comment by jlongster** [comment]
@skevy The idea of my article was to show that all of these hot loaders have the same functionality: use webpack's HMR to get module updates. How you apply the updates should be easy to configure.

Theroetically, if we extract out the ES6 class patching, I could add an option to monkey-hot-loader to tell it to use just that. If you used that, you would basically (I think) have react-hot-loader without the React-specific stuff like `forceUpdate`.

This is all pretty theoretical though, and maybe that much abstraction isn't worth it. If it's just a few lines in RHL might be worth just doing it there, but it's @gaearon's project so it's up to him.

**Comment by skevy** [comment]
Yah. Definitely on the same page.

I will prototype it, and see how gross it is.

**Comment by jlongster** [comment]
Let me know what you end up with. You could fork RHL too and show @gaearon how much complexity it would add. If not much he might be convinced.

If you end up integrating ES6 class patching with monkey-hot-loader, I'd love to see how well that works!

**Comment by RickWong** [comment]
About server-side hot-loading check out https://www.npmjs.com/package/piping

I use it in my starterkit https://github.com/RickWong/react-isomorphic-starterkit to enable instant code updates, both on the server and on the client (using React Hot Loader).

**Comment by jlongster** [comment]
@RickWong I'm confused, isn't that still killing the entire server and restarting it basically? That loses a lot of hot reload benefits.

**Comment by RickWong** [comment]
@jlongster It reloads the application, but not restart the Node server. In practice that means the changes are available instantly < 1s compared to a full node-supervisor / forever restart which can take 2 or 3 seconds. But don't take my word on it, try it out yourself if you have a minute or two. Combined with webpack for client-side hot reloading, developing web applications has never felt so interactive before.

**Comment by jlongster** [comment]
@RickWong that is cool, but that wouldn't be very hard to do with webpack itself. In the top-level module, you only start the server if there isn't one already on `module.hot.data`, otherwise use the existing one if reloading.

`piping` does give you that if you don't already use webpack for the backend, which is cool! :)

What I really want though is a true REPL. It's too useful to declare some state for debugging and build it up between evals, which is real interactivity. Plus, if you happen to have any module-level state (which you shouldn't do that very much, but can be useful for something like caching), you will lose that. See my post here: http://jlongster.com/Backend-Apps-with-Webpack--Part-III

I don't mean to take away any of the current efforts of backend live reloading, I just pine for a Lisp-style REPL, but I'm about to start using ClojureScript anyway so I'm not too concerned with it now. :)

**Comment by steida** [comment]
Yeah, I'm using piping for over two years in https://github.com/steida/este.
