### ISSUE TITLE
HMR fails on nested routes react-rotuer-config 

### ISSUE THREAD

**Issue by AhmedKorim** [gaearon/react-hot-loader#1248]
If you are reporting a bug or having an issue setting up React Hot Loader, please fill in below. For feature requests, feel free to remove this template entirely.

### Description

Hot reloading working fine but with react-router-config, it does full browser reload
I've tried adding <base href="/" /> to the head but it didn't work, eventually, it working after capturing module.hot and accepting

### Expected behavior

Expected HMR .  to work normally on nested routes using react router config

### Actual behavior

browser full reload and had to add
```
if (module.hot)
    module.hot.accept()
```
on routes file (config that reacts router config uses to render routes )

### Environment

React Hot Loader version:

Run these commands in the project folder and fill in their results:

1.  `node -v`: 10.15.3

2.  `npm -v`: 6.4.1

**Comment by theKashey** [comment]
That means that some updates are propagating in using a _different_ module chain, not thought `hot`, or not only thought it. That's why you have to add `module.hot.accept` into the route-config.

All updated should go through `hot`, thought the single module you might `accept` _properly_. Doing something like `module.hot.accept()` basically suppress update, as long as no necessary action to actually _update_ is not taken. See for details - https://medium.com/netscape/how-to-hot-load-react-component-in-7-days-part-1-webpack-d8b77eea61eb

This is more bound to HMR itself, and there is nothing RHL could fix.
