### ISSUE TITLE
Live reloading stops after a specific error

### ISSUE THREAD

**Issue by vitalybe** [gaearon/react-hot-loader#129]
Repro steps:

1. `git clone https://github.com/vitalybe/goodread-friends`
1. `npm install`
1. `gulp`
1. Connect to: `http://localhost:8080/#/`
1. Change `.\src\app\components\hello.jsx` some JSX and verify hot-reload is working
1. Change  in the same file `render` to `renderrr:` - Error is thrown as expected
1. Change it back to `render:`
1. Any further JSX changes are ignored, the console prints output as if it does, however: 

```
client:19 [WDS] App updated. Recompiling...
client:65 [WDS] App hot update...
only-dev-server.js:62 [HMR] Checking for updates on the server...
log-apply-result.js:20 [HMR] Updated modules:
log-apply-result.js:22 [HMR]  - 8
only-dev-server.js:48 [HMR] App is up to date.
```

I could not reproduce this issue in `react-hot-boilerplate`

**Comment by gaearon** [comment]
In React Hot Boilerplate, I'm using ES6 classes. In this case this specific error (lack of `render`) is only checked when the instance is force-updated on the next tick.

In your project, the lack of `render` is checked right in `createClass` call and it blows up the module definition.

In theory we could try to recover from errors during module definition, but I'm not going to make functional changes to RHL at this point, since it's going to be converted to use a new engine in a few months. This new engine will be easier to modify (as it will be covered by tests), so we might support something like this there.

For now, it's non-actionable, so I'm closing. Thank you for bringing this to my attention, so that I'll try to do better in the next engine.
