### ISSUE TITLE
"Hooks reset" not working

### ISSUE THREAD

**Issue by nfarina** [gaearon/react-hot-loader#1393]
### Description

First off, thanks so much for your tireless work on this project! This is the most essential dev tool I use.

In the README, it states:

  > Hooks would be reset if their order changes. Adding, removing or moving around would cause a local tree remount.

Sounds amazing! This is exactly what I want. However, it doesn't seem to be doing this.

### Expected behavior

I see in the source for `react-hot-loader` this promising line:

```
⚛️🔥🎣 Hook order change detected: …
```

But I never see that. I've also set a breakpoint on that line and it's never called.

### Actual behavior

Changing hook order or adding/removing hooks results in the usual errors from React:

  - "Should have a queue."
  - "Rendered fewer hooks than expected."
  - etc.

### Environment

React Hot Loader version: `4.12.17`

Run these commands in the project folder and fill in their results:

1.  `node -v`: `v12.11.0`
2.  `npm -v`: `6.11.3`

Then, specify:

1.  Operating system: macOS `10.15.1`
2.  Browser and version: Chrome Canary ` 80.0.3965.0`

### Reproducible Demo

Minimal project: https://github.com/nfarina/hooktest

**Comment by theKashey** [comment]
👍, could not resist so perfect issue. Looking into it right now...

**Comment by theKashey** [comment]
Founds issues:
- `hot-loader/react-dom` 16.11(as well as 16.10) has incorrect logic for `updateChild`. The old `Button` and were not compared, as long as they are already equal. Introduced by @Bnaya in #1355
- the root cause - components ARE equal, as long as they were "made" that way. Introduced by me in #1348


Solutions:
- update `patch` to remove `current$$1.elementType === element.type` condition
- roll back fiber auto update. Might reintroduce #1342, not there is no choice

**Comment by Bnaya** [comment]
😪🤭

**Comment by theKashey** [comment]
4.12.18 has been released

**Comment by nfarina** [comment]
Amazing!! Thanks so much for fixing this so quickly—the Hooks Reset feature is a *major* time-saver. Cheers.
