### ISSUE TITLE
Sometimes hot() is needed not only for the root component

### ISSUE THREAD

**Issue by mikhailrojo** [gaearon/react-hot-loader#1586]
### Description

What you are reporting: Issue

### Expected behavior

In large projects with dom-react-router, React.lazy and many components I wrap the root component in hot() and expect all children of that component will be hot-reloadable.

### Actual behavior

But in some cases i get full page reload with
 `The following modules couldn't be hot updated: (Full reload needed) This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves.`.

To solve this issue I need to wrap those components in hot() too - to teach(?) them how to be reloadable.
After I wrap them - they are fine and work as expected(without full reload).

### Environment

React Hot Loader version: 
"react-hot-loader": "^4.12.21"
"react-router-dom": "^5.1.0",

### Question:

1. Is it expectable behaviour? Do we need to wrap descendant React components  in hot() if they already have hot()-parent?
2. Why is it happening? Why some components don't know how to reload and supposed to be wrapped?
3. Is there a simple way to debug such problem? Perhaps to set up in some easy way a logger, which could tell you what is the cause of full page reload, what breaks it?

thank you

**Comment by theKashey** [comment]
1. Yes, that is expected behaviour of __webpack__.
2. This is happening because the are used __not only__ in a hot()-parent. 
3. The actual message from webpack about "full reload needed" should include the information how "update" was able to reach the root from the source file. Just check it to understand why you have this problem.

In short - every module might have __more that one parent__ - you are accepting update in one parent, but not in another.

**Comment by mikhailrojo** [comment]
Thank you @theKashey 
My take away:
- In console I see  the chain of files(!) how the hmr event bubbles up (from which components did it go)( lookes like ./src/One.js -> .src/Two.js -> 0)
- Add hot() to the ones in which are in such a chain
- Know that hmr event bubbles thought files not components

Closing it
