### ISSUE TITLE
hmr no work in React.PureComponent

### ISSUE THREAD

**Issue by zhaopan-pan** [gaearon/react-hot-loader#1900]
### Description

It's strange that my component can't trigger HMR normally in React.PureComponent, but it's normal in React.Component.
HMR works fine if I replace React.PureComponent in Routes with React.Component.
Has anyone encountered such a problem?

### Expected behavior
React.PureComponent can be use HMR

### Actual behavior
![bug](https://user-images.githubusercontent.com/30975538/211707636-1676b5d0-b388-4f29-b8d8-0c93ee2496f7.gif)
![20230111105644](https://user-images.githubusercontent.com/30975538/211708202-a237bc5e-9162-462d-8654-0f9cb84713aa.jpg)

### Environment

"react-hot-loader": "^4.13.1",
"react": "^17.0.2",
"webpack": "^4.44.2",
"webpack-dev-server": "^3.11.2",
node: v14.19.1
chrome:108.0.5359.124

**Comment by theKashey** [comment]
React-Hot-Loader has a special logic to trigger force re-render in PureComponents and cause update of affected components... which was never tested for React 17. So something might got broken here and there.

Unfortunately, the fix is not coming, at least from my side - https://github.com/gaearon/react-hot-loader/pull/1848

**Comment by zhaopan-pan** [comment]
all right, I think it's time use react-refresh to replace RHL. 
thank you for your reply
