### ISSUE TITLE
Warning: Factory.type is deprecated.

### ISSUE THREAD

**Issue by smakhtin** [gaearon/react-hot-loader#238]
I just integrated react-hot-loader into my project and keep getting Warning: Factory.type is deprecated. How can i fix this?

**Comment by gaearon** [comment]
It should be solved in the rewrite that I’m working on. No plans to backport the fix to older versions so you’ll probably need to either wait it out, or hold off from using React Hot Loader until then. I’m closing because this is not actionable–keep your eyes on the repo and try RHL 3 when it’s available!
