### ISSUE TITLE
Can't find dist folder

### ISSUE THREAD

**Issue by adanielyan** [gaearon/react-hot-loader#297]
I ran npm install and then npm start. Everything works fine, the hot reload works as expected. However, I can't find the dist folder or bundle.js anywhere in the system! I searched through the entire hard drive, the file is not there. But it somehow manages to load in the browser and work. 

I tried it on mac and also in nitrous.io. Same thing.

Can someone explain what's going on?

**Comment by zivl** [comment]
this issue is not related to `react-hot-loader` specifically. You rather ask this in an appropriate `webpack` forum.
Anyway, to address your issue, while in **dev** mode, `webpack` can build the `bundle` to memory and not to a specific path on your file-system. That depends on your `webpack.config` settings.
see more info here: http://webpack.github.io/docs/configuration.html

**Comment by adanielyan** [comment]
Thank you zivl, I appreciate your response. Will take a look at webpack config.
