### ISSUE TITLE
react-hot-loader 3 babel plugin cased to the bundle.js size increased.

### ISSUE THREAD

**Issue by xuqingkuang** [gaearon/react-hot-loader#357]
When using babel plugin:

    -rw-r--r--  1 kuangxuqing  staff   2610049 Sep 12 11:20 bundle.js

When disabled babel plugin:

    -rw-r--r--  1 kuangxuqing  staff   2595799 Sep 12 11:19 bundle.js

The plugin increased 14k of the production built file, how can I optimize it ?

**Comment by calesce** [comment]
The plugin [shouldn't](https://github.com/gaearon/react-hot-loader/blob/next/src/babel/index.js#L33) do anything in production, are you using `NODE_ENV=production`?

**Comment by xuqingkuang** [comment]
@calesce Yes, I enabled `NODE_ENV=production` in webpack config.

After checking I found there are a lot of `__REACT_HOT_LOADER__.register()` calling in built file, there's a test project[1], please take a look.

[1] https://github.com/xuqingkuang/react-redux-boilerplate

BTW: In the test project still using beta 1, but the behavior as same as beta 3.

**Comment by calesce** [comment]
After testing with your project, process.env.NODE_ENV was undefined in the Babel plugin when running `npm run build`. I investigated, and it's because `DefinePlugin` gets run after `babel-loader`, see [here](https://github.com/webpack/webpack/issues/2121).

I changed build to `"build": "NODE_ENV=production gulp production"`, and it stripped those `register()` calls, and the build size was about 4k smaller than before.

Thanks for pointing this out! I'm sure there's more people who have this issue without realizing it, so we should document it better. Please re-open if this doesn't solve the issue on your actual app.

**Comment by xuqingkuang** [comment]
@calesce Good, thanks a lot!
