### ISSUE TITLE
@3.0.0-beta.4 doesn't work if React is external

### ISSUE THREAD

**Issue by awaw00** [gaearon/react-hot-loader#364]
Same as #53 but in v3.

**Comment by awaw00** [comment]
@calesce 

Thanks for your response.

I've created a example repo [here](https://github.com/awaw00/react-hot-loader-test), and I found if I used react-router as a external library(use script tag), when components under my routes has changed, react-hot-loader couldn't replace the module exactly.

Sorry for my poor english.

**Comment by pedronauck** [comment]
Is happening the same error here 😐 When we put react as external script, hot loader it's getting confusing and can't reload files... We're following the same structure above.

In our case, we need react as externals because webpack is bundling multiple instancies of react, and we get a reference error, so we need it as a external. It's so funny, because this just happened when we put our projects in a monorepo and set the `CommonsChunkPlugin`.

**Comment by calesce** [comment]
@awaw00 thanks for the repo, it looks like the issue is React Router also being external, if you remove it from externals and have it in `node_modules`, the issue goes away. I'm not sure whether we'll be able to support having non-React component libraries in externals.

@pedronauck do you have a simple reproduce project? as I said above, React being external isn't an issue here.

**Comment by calesce** [comment]
@awaw00 I did some additional testing, and it looks like the issue is React Router being external specifically. I tested with other 3rd-party components ([react-datepicker](https://github.com/Hacker0x01/react-datepicker)) being external, and they were hot replaced properly.
