### ISSUE TITLE
Hot reloading required full reload when errors occur in JSX interpolation

### ISSUE THREAD

**Issue by dcurletti** [gaearon/react-hot-loader#373]
I have a project that follows the [react-hot-boilerplate Next branch](https://github.com/gaearon/react-hot-boilerplate/blob/next/), but whenever it tries to interpolate JS code with errors, it requires a full page reload.

Below I have an example where I start by returning valid html

```javascript
return (
        <span>hello</span>
    )
```

Hot reloading works great, until I insert an undefined variable into the HTML to be interpolated: 

```javascript
return (
        <span>{undefinedVariable}</span>
    )
```

At this point, I get the following error:
![image](https://cloud.githubusercontent.com/assets/7329041/18693350/05af6988-7f56-11e6-901c-bf9f384e88ca.png)

Once that error happens, I have to do a full page reload to get it to work again.  

What is strange is if I create JS errors *outside* of rendered HTML, such as inside of the `render` method and before the return, the files hot reload perfectly.

```javascript
  render() {
    asdfasd
    return (
        <div>hello</div>
    )
  }
```

![image](https://cloud.githubusercontent.com/assets/7329041/18693502/fa866b3c-7f56-11e6-9df2-8d778a42c349.png)

**Comment by calesce** [comment]
Hi, I think what you're seeing is related to #164. We're currently using React's [`unstable_handleError`](https://github.com/gaearon/react-hot-loader/blob/next/src/AppContainer.dev.js#L43) hook, which currently only catches render errors on initial mount. They're working on also catching render errors on updates in https://github.com/facebook/react/pull/6020, which would make the redbox show up consistently.

In your first example, if you refreshed the page you'd see the red box with `undefinedVar is not defined`, since that's when React would first try to mount that component. Similarly, if you triggered the second example after the component first mounted, you'd see the uncaught exception in the example.

I know Dan's talked about just building the error catching into [React proxy](https://github.com/gaearon/react-proxy) instead, so that's the direction we might take instead. Sorry you're hitting the rough edges right now. 😕

**Comment by dcurletti** [comment]
Yup, that sounds exactly what is happening. 

Thanks for the link and for responding so quickly.
