### ISSUE TITLE
Production hot reloading?

### ISSUE THREAD

**Issue by KyleAMathews** [gaearon/react-hot-loader#38]
Not sure if you saw your shoutout yesterday — http://rauchg.com/2014/7-principles-of-rich-web-applications/ but this got me thinking if hot reloading of modules would be possible in production. Because that'd be really sweet.

Thoughts?

/cc @sokra

**Comment by geekyme** [comment]
can you show me how I could implement a custom hot server @gaearon

**Comment by gaearon** [comment]
Can you describe your use case?

**Comment by geekyme** [comment]
My use case will for a commenting feed where people will add comments to feeds in real time. I want to be able to ship new code and update the users' UI using HMR. If HMR is not possible at this stage, maybe live reloading all connected users' browsers might work.

**Comment by sokra** [comment]
@geekyme Technically this is possible... Some preconditions:

* Compilation (currently webpack/webpack#295) must happen on the same absolute path. (So maybe in a docker container or vm)
* You need to store records
* You need a mechanism to notify the client about updates (Maybe over an existing WebSocket connection)
* You need to implement HMR management code in your application. (Something similar to `webpack/hot/dev-server` but integrated with your app and update notification)
* You need to be careful about changes to a components state (because react-hot-loader keeps state). @gaearon maybe react-hot-loader should handle this. I. e. each component can export a component version. When it increases react-hot-loader should do reinit/remount the component.

**Comment by gaearon** [comment]
Closing, as not really an issue.
I don't think hot reloading in prod would work because

1) React components are stateful, this works between minor updates but any non-trivial update will have some breakage.
2) There's a perf hit to using RHL because we're proxying each method. You should always turn it off in prod builds.

**Comment by maxwaiyaki** [comment]
I'm having a problem where for a minority of my users, whenever I push new code, they have to hard refresh their browsers to get the new changes. Is there a way to mitigate this??

**Comment by theKashey** [comment]
Well, yes. But not like React-Hot-Loader.
Please check [Module Federation](https://github.com/webpack/webpack/issues/10352#issuecomment-628958509) - it will help not only *hot update* some packages, chunks or modules, but also *deliver* the update to all customers, SSR included.

**Comment by ScriptedAlchemy** [comment]
I’m working on a ssr example. But the repo I’ve been trying it on also streams code from s3 - adding more complex than necessary. 

I’ll update my ssr example to hot reload in production. I believe it’s relatively trivial with module Federation. 

Module Federation supplies evergreen code at runtime. Without redeployment. It’s a universal solution. And works with any module type or any file webpack can process today (images, css, loaders) 

I’m also able to preserve state and context of the whole application, however replacing a module would likely require react context or the parent to hold its state. If you want the true hmr without page reloading - all you need to do is reload the interface. Interface and webpack handles the rest. 

This has already been merged and pushed to npm under webpack 5 beta 16.

https://github.com/module-federation
