### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#385]
Just sharing some thoughts from another thread: https://github.com/gaearon/react-hot-boilerplate/issues/97. I know many people think I abandoned this project so I thought it’s a good chance to explain my position.

**Comment by danmartinez101** [comment]
@calesce @gaearon  
Looking for a place where babel-preset-react-hmre can either be inlined to another codebase that makes sense, or someone that is using it to have commit and npm access. 

https://github.com/danmartinez101/babel-preset-react-hmre/issues/46#issue-180449718
One recommendation so far was a place like the babel monorepo. 
I was also wondering how / if it would fit into this side of the equation?  

Or do you have other ideas than merging it into somewhere maybe? It is basically a dozen lines of config that gets downloaded quite a bit.

**Comment by calesce** [comment]
@danmartinez101 I don't think that merging it here is the best place, since this repo has only been used for React Hot Loader 1 and 3. Also, React Transform and associated tools have been deprecated, and AFAIK no one else is working on them.

Either way, RHL 3 is much simpler for end-user [Babel configuration](https://github.com/gaearon/react-hot-boilerplate/blob/f134ff335d26f1b0369e65a9309b4ec1a38a2581/.babelrc). Hopefully most people will either move to that or vanilla Webpack HMR in the future.

**Comment by danmartinez101** [comment]
Ah, wow, that is how far removed I've been... I got the different implementations mixed up. If no-one is maintaining the versions that that preset goes with... everything is pretty simple. 

Thanks for straightening me out!

**Comment by Rokt33r** [comment]
I want to help RHLv3. Could you give me some points where should I start?

**Comment by neoziro** [comment]
@Rokt33r you can contact me
