### ISSUE TITLE
Problems with not injecting changes

### ISSUE THREAD

**Issue by th3fallen** [gaearon/react-hot-loader#418]
You requested a issue for this so here i am :P 

### Description

What you are reporting:
Hot-loader v3 reports changes but forces to reload

### Expected behavior

What you think should happen:
should behave like v1 and inject the changes

### Actual behavior

What actually happens:
![](http://th3fallen.d.pr/19Vz.jpg)

### Environment

React Hot Loader version: 3.0.0-beta.6

Run these commands in the project folder and fill in their results:

1. `node -v`: v7.1.0
2. `npm -v`: 4.0.2

Then, specify:

1. Operating system: 10.12.2 beta (16C48b)
2. Browser and version: Chrome Latest

### Reproducible Demo
i demo is not possible due to scale but here are the relevant files 
https://gist.github.com/th3fallen/bba636b4bf1045188aa3a02a04b27a4b

**Comment by calesce** [comment]
Are you using a separate `.babelrc`? I think `babel-loader` needs plugins to be defined as `query.plugins`. We have problems when not using ES2015 preset (see #313), so maybe that's what your issue is.

Also, instead of re-importing `Main.js`, you'll need to re-import `routes`, since that module is the "entry point" to other component modules. For React Router stuff see #249.

**Comment by calesce** [comment]
Hey, I'm closing this out due to lack of response, and I gave you a few potential solutions. Let me know if those don't work.
