### ISSUE TITLE
Why does react-hot-loader 3.0.0-beta.6 require a patch ?

### ISSUE THREAD

**Issue by adi1133** [gaearon/react-hot-loader#480]
I see that `react-hot-loader/patch` is used to setup a global object `global.__REACT_HOT_LOADER__` . 
I think the same thing can be achieved by using require statements.

What are the reasons for using a global object in the current implementation ?

**Comment by calesce** [comment]
Dan would know exactly why, but I'd guess it's because every source code file potentially has a React component that could be hot-reloaded.

`__REACT_HOT_LOADER__` could be exported from a module, but you'd have to then add imports to every other source code file at build-time. It's probably not worth the overhead to avoid a global just for a development-time tool.

**Comment by adi1133** [comment]
If you use the `react-hot-loader/babel` on all jsx files it could only add the import into files containing react components.

**Comment by calesce** [comment]
Many people don't use the `.jsx` extension for files with JSX, and it's very difficult to statically detect React components at compile time. That's why we added the new Babel plugin/Webpack loader to inject code that "tags" components at runtime. See [Dan's article on hot reloading](https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf#.prrf4nccm) for some background.

**Comment by calesce** [comment]
Closing this because we probably won't change much from the current approach. If you have a solution that works just as well or better with a cleaner approach, please open a PR.
