### ISSUE TITLE
Usage outside Webpack?

### ISSUE THREAD

**Issue by Daniel15** [gaearon/react-hot-loader#61]
This project looks awesome! I'd love to use it in my job at Facebook, however we're using an internal PHP-based build system rather than Webpack. I'm wondering how tightly-coupled this project is to Webpack, and if it could ever be used without Webpack. Could it hook into [fb-flo](http://facebook.github.io/fb-flo) at all?

Thanks!

**Comment by gaearon** [comment]
I'm not sure about fb-flo because I haven't taken a close look at it.

This is *not* tied to Webpack. I extracted Webpack-independent part into [React Hot API](https://github.com/gaearon/react-hot-api), and that's what powers the homepage.

There are three ingredients to making this work:

* Patching React classes on the fly with a new version and tricking React into thinking it's the same class so it doesn't bail out of reconciliation (that's what [React Hot API](https://github.com/gaearon/react-hot-api) does);
* A generic system for modules to register “update handlers” for any module and bubble them up `require` hierarchy until some module “knows” how to accept its update (that's what Webpack's [Hot Module Replacement](https://github.com/webpack/docs/wiki/hot-module-replacement-with-webpack) is);
* A build step where we generate a React-Hot-API-calling update handlers for component modules.

So it's theoretically possible to do (2) and (3) with any other build system that can emit partial updates (for changed modules and their dependencies), can replace modules with new versions execute user-defined code when module is updated, and transform code.

*In fact* even React Hot Loader is not very tied to Webpack itself. Webpack HMR has quite a generic API, and you can implement it in another module system. It looks like a set of methods on a special `module.hot` object (which is only available when HMR is enabled): `module.hot.accept(handler)`, `module.hot.accept(dependency, handler)`, `module.hot.dispose(handler)`, etc. [Here are more examples from Webpack's website with API description](http://webpack.github.io/docs/hot-module-replacement.html). I'd be thrilled if more build systems adopted this API.

See also [an older technical intro post](http://gaearon.github.io/react-hot-loader/2014/07/23/integrating-jsx-live-reload-into-your-react-workflow/) for more context.

**Comment by gaearon** [comment]
@sokra can probably explain HMR module system requirements better than I do.
