### ISSUE TITLE
Specifying Host for `.hot-update.json` & `.hot-reload.js`

### ISSUE THREAD

**Issue by ChuckJonas** [gaearon/react-hot-loader#641]
I have a bit of an odd use case... I'm trying to get hot reloading working on a remote PAAS server (Salesforce).

IE I have a page on a server that is pointed to my localhost.  

`<script src="https://localhost:8080/app.js" />`

Everything seems to be working up until the point where `.hot-update` & `.hot-reload.js`  are requested.

Instead of requesting them from my localhost (running `web-pack-dev-server`), it request them from the remote server:

`https://my-remote-server.com/ec88b24d1800c4ce075d.hot-update.json`

Obviously, this returns a 404.

Is it possible to somehow configure the host for these requests so they would instead go to:

`https://localhost:8080/ec88b24d1800c4ce075d.hot-update.json`

I know CORS will be an issue but I think I already have that part setup correctly.

Thanks!

**Comment by neoziro** [comment]
Hello, you can configure [webpack-dev-server in a proxy mode](https://webpack.js.org/configuration/dev-server/#devserver-proxy).

**Comment by meszaros-lajos-gyorgy** [comment]
I have the same issue trying to connect webpack dev server with html generated by PHP. The link no longer points to a valid location in the document, so can anyone give a short example on how to configure the devServer option?

The goal would be to make webpack hmr not use the hostname from the html (I'm using a virtual host for this and not serving the content from anything remotely close to localhost:8080), but instead use the host given in the devServer config.

`devServer.host` is not working in this case, because webpack wants to start a server there instead of just using it as part of the url schema used when update is triggered.

**Comment by meszaros-lajos-gyorgy** [comment]
Found a solution: just specify the full url into `output.publicPath` and set both `devServer.public` and `devServer.publicPath` to `""`.

Source of idea is from: https://github.com/webpack/webpack-dev-server/issues/1385#issuecomment-502758062

**Comment by dimti** [comment]
If you use vue bundle in your separate frontend domain and use vue dev server with connect scripts from "http://localhost:8081/js/app.js"
If you search how to work `*.hot-update.json` on `vue-service-cli` with hot reloading, write into your `vue.config.js`:
```
    publicPath: 'http://0.0.0.0:8081/',
    devServer: {
        disableHostCheck: true,
        headers: { 'Access-Control-Allow-Origin': '*' },
    },
```

Need options: `publicPath` (that is vue cli option) and `devServer.headers` - in that tandem hot-update.json calling from vue dev server host.
