### ISSUE TITLE
Do not hot reload non-react modules

### ISSUE THREAD

**Issue by vishnevskiy** [gaearon/react-hot-loader#65]
I tried to point the react-hot to only be used on files in my component files, but it still seems to attempt to hot reload when I change some of my Store files (but not all oddly).

The only way I have found to fix this is to do module.hot.decline() in my stores but doesn't seem to work. Is there anyway to fix this?

**Comment by gaearon** [comment]
Normally hot updates bubble. This means if components `require`s a Store, and you change the Store, since it can't handle the update on its own, the update will propagate to the components. Components then handle the update with hot loader. Is this what you're experiencing?

This works really well for stateless modules. For example, if you have a mixin, or an utility module, if it is only used by components (or modules that themselves satisfy this condition), then hot replacement works nicely, because update version of components will use the new version of dependency.

It kinda falls apart with stateful modules like Stores because their new versions will not contain any state, and components are still subscribed to the old versions. Currently, I don't solve this in any way and just refresh manually after I change Store code. In the meantime, I'm working on [flux-hot-loader](https://github.com/gaearon/flux-hot-loader) which is supposed to fix this problem for Stores.

Does this answer your question? Or do you have some other kind of problem?

**Comment by vishnevskiy** [comment]
That mostly answers my question.

I thought it was a bug honestly that modules that weren't accepted caused a hot reload rather then a page reload. But since it seems that it is by design I guess I can just call decline on them manually for now.

I will keep an eye out for the flux hot loader.

Thanks!

**Comment by gaearon** [comment]
>I thought it was a bug honestly that modules that weren't accepted caused a hot reload rather then a page reload.

I think you're right about this not being quite “by design” of HMR system. We're kind of cheating in React Hot Loader by claiming components can *always* accept updates of themselves when in fact it's not strictly true. Unfortunately there is no way for us to know which of the modules are stateful, so we're making a compromise.

One thing you might be interested in is the Manual Mode. I haven't properly documented it because I'm wating for React Router 0.12 to come out with `router.replaceRoutes`. If you say `react-hot?manual` in Webpack config instead of `react-hot`, the loader *will not* generate any `module.hot.accept` calls. This means you're free to accept (or not accept updates) in any file, with any custom logic. My use case for it is putting `module.hot.accept` on `routes.js` file and hot-replacing the router configuration when any route handlers update, but you may want to use it in some other way.
