### ISSUE TITLE
This project is dead and you're killing it.

### ISSUE THREAD

**Issue by AaronFriel** [gaearon/react-hot-loader#656]
This is a mess, @neoziro, @gaearon. 

My PRs are being closed for poor reasoning and faulty logic, and while trying to submit *patches to make this project work with React 16*. I'm told by @neoziro that I need to re-implement or re-export things he removed from the project, and my commits are not even being read as he peppers my PRs with questions before closing them.

I'm done, I'm forking this project because the maintainer @neoziro is a jerk and killing this project.

# Case 1

![image](https://user-images.githubusercontent.com/788800/31308383-d1568ee2-ab3b-11e7-9c7d-56b3c9a6436d.png)

![image](https://user-images.githubusercontent.com/788800/31308392-dfe4651a-ab3b-11e7-8c79-4bcfa33b8381.png)

# Case 2

![image](https://user-images.githubusercontent.com/788800/31308366-740222f6-ab3b-11e7-9fe3-6be6fe17f0db.png)

![image](https://user-images.githubusercontent.com/788800/31308376-a5fafd6e-ab3b-11e7-8599-b779da360f5a.png)

**Comment by gaearon** [comment]
Hey, there's no need to be aggressive. I'm sorry you're frustrated but I've been busy with React 16 *itself* and I think it's obvious this was a higher priority.

Unlike many others who only complain, @neoziro volunteered to help maintain the project. If you’re not happy with how he’s doing it, there are polite ways to raise an issue and let me know. I will take a look at this after the weekend but I encourage you to be more friendly and assume everything is being done in good faith in the future.

Getting emotionally charged hyperbolic reports like this on weekends is why people quit open source. Even if you’re technically right please reconsider your attitude. Thanks.

**Comment by gaearon** [comment]
Also, calling people names will get you banned from this project, regardless of how technically right you are. Please edit your post. Thanks.

**Comment by AaronFriel** [comment]
I respectfully decline, he is *acting like* a jerk, and it's behavior like his which pushes people out of OSS.

**Comment by gaearon** [comment]
Can you point out specific examples where he is calling you names or is being hostile? Technical disagreement or misunderstanding doesn't count.

Also, I'm pretty sure you called me a jerk too. Can you clarify how I deserved this from you? Have we even interacted before?

**Comment by AaronFriel** [comment]
I'm sorry, I retract that and I'll edit it to clarify that he is acting like a jerk. And this is beyond technical disagreement, he closed #652 and #653. The latter he closed, saying we'll focus on #652, which remains closed even after I clarified why I submitted it.

He left needling comments on #654 that demonstrated he:

1. Did not read the commits in the PR, see: https://github.com/gaearon/react-hot-loader/pull/654#discussion_r143324852.
2. That I had to re-implement functionality he removed in #639, see: https://github.com/gaearon/react-hot-loader/pull/654#discussion_r143324873
3. Tests already throw errors in the console, as demonstrated by #657, but he applies a double standard to PRs from others: https://github.com/gaearon/react-hot-loader/pull/654#pullrequestreview-67827427

**Comment by gaearon** [comment]
I’ll look at the technical side of this on Monday. Let’s just be clear misunderstandings happen on every project.

I understand you were frustrated but there are always ways to express it in a way that isn’t a personal insult. For example your issue could just be a collection of facts: you could state you don’t understand the logic behind these decisions, but not jump to calling us names or declaring a project “dead”. This could be your mistake, @neoziro’s mistake, or a combination of factors. Maintainers are just people, they make mistakes. Nobody hurt you or insulted you. 

If you assume everyone operates in good faith and isn’t intentionally trying to be a jerk to you, it is much easier for everyone to come to a mutual understanding. Getting your PR closed can be frustrating but if you take this personally, you are putting unreasonable pressure on maintainers. If we’re not allowed to close PRs or make mistakes without getting emotional abuse in return we might not find it sensible to continue investing our effort in these projects.

**Comment by YasserKaddour** [comment]
Assuming good faith is a fundamental principle on Wikipedia and it should  be the same for any collaborative project like open source software.

@AaronFriel I hope a little bit of reading on this principle will help you calm your nerves.

https://en.wikipedia.org/wiki/Wikipedia:Assume_good_faith
https://opensource.org/node/877

**Comment by neoziro** [comment]
@AaronFriel I will not comment about your behaviour. I think that you can figure out by yourself that it does not help and that it is not in your favor.

I will explain each point:

1. Yes I haven't see it. I didn't hear about this problem, but I am new, I could have missed something. I think it is better to make it in another PR and to release it in a v4 rather than in a v3.
2. Yes I removed it but I didn't publish it and I fixed my mistake (updating documentation). I asked you politely to make a one line alias to avoid breaking all existing installations and a tons of issues.
3. I am sorry but you are wrong, tests are not failing, there is an "error" log because we do not mock "console.error" and it is actually what we want to test.

I closed your PR because all your commits was already in #654. We do not need 3 PR with similar commits.

**Comment by AaronFriel** [comment]
1. Patches to make React-Hot-Loader work cross-platform require a semver bump even though 3.0 hasn't been released yet? Wait, why did you merge `HotContainer` then? (See 2.)
2. @Neoziro is externalizing responsibilities to make fixes to things he changed. He merged #639, and because I'm submitting patches it's my responsibility to fix other things?
3. You're right, but on Windows even on `master` I get many, many errors. I haven't had a clean test suite run yet. I can understand why you would want contributors to update your test suite, but again, I think you're just externalizing issues instead of accepting patches to Make Things Work.

Note the double standard, @gaearon. Greg will merge patches that break semver and make existing documentation wrong, but others cannot. Then, when I submit a PR, it's my responsibility to add shims to fix his semver breakage? Why is that my responsibility?

This externalizing of responsibility and increasing the burden for accepting patches is unacceptable in an OSS project, and it's bad behavior. It's goalpost moving in terms of requiring ever higher burdens on contributors who want to submit fixes, and it means people like me get frustrated and decide to take our ball and go home.

I didn't *want* to spend several hours understanding the test harnesses you built and learning new tools, I wanted to submit patches that enable code to *even work*. The test harness is **totally broken** on React 16, and apparently it's my job to fix that too.

**Comment by neoziro** [comment]
Open source is collaborative, if others do not make things right it is your responsibility to explain what is wrong and to fix it. Insulting or creating this kind of issue does not help in any way.

1. Yes v3 alpha / beta has been released more than a year ago, it is widely used and its our responsibility to not break every existing installation. I merged HotContainer because I plan to release a v4 including React 16 support.
2. Yes it is your responsibility to not break this repository by updating documentation that does not reflect what is published on npm.
3. Majority of users (including me and @gaearon) use MacOS. If you use Windows, it is great because you can fix things that we cannot easily fix on our side. But it is also your responsibility to not break CI and to fix it if you did. I will not merge a red pull-request.

Also to mention your patch (dc1daaa61bddf51a2f1fa0a35d533ceadba44055) fixed by a breaking change. I think we can fix it without making a breaking change, and fixing something means adding a test to reproduce the bug. I do not see any test in your PR.

I can see that you do not want to spend several hours understanding how to run `jest` and I do not expect you to fix React 16.

If you want to fix issue related to babel.js and windows, you can still do it by following the right way:

1. Reproducing bug in a test or explain it in an issue to give opportunities to others to reproduce it
2. Trying to find a way that do not fixing it by a breaking change
3. Making a PR that fixes this issue without bumping, adding a VS Code settings and breaking existing tests

**Comment by romulof** [comment]
About the `HotContainer` rename that I suggested:
1) I totally agree with @neoziro revert: Deprecation must come before change;
2) None of those changes (including the revert) were published on NPM;
3) Even if it was published, v3 was on Alpha dist-tag. Users of this kind of release must be open to changes;

**Comment by AaronFriel** [comment]
The unreasonableness continues. @gaearon, I do not think @neoziro is even thoroughly reading any commits. **There is no reasonable way for me to produce a JavaScript test for dc1daaa61bddf51a2f1fa0a35d533ceadba44055**.

**Comment by AaronFriel** [comment]
![babel](https://user-images.githubusercontent.com/788800/31475004-eea682b4-aec3-11e7-94d1-d2cea402ef60.gif)

**Comment by AaronFriel** [comment]
It honestly makes me mad that I even had to download some gif screencast software to produce that silly artifact. This is the **second** time @neoziro has nitpicked that commit without quite reading what I've written in the commit.

And it makes me mad that he's placing demands on other people to adhere to semver but his own PRs do not. He can change the features and leave the repository in a broken, mismatched docs and API state for weeks and he can foist the responsibility of correcting this on the first person to make a serious effort to get the project to target the release version of React. Sorry, "the tests are broken" is an unhelpful critique when *of course* they're broken, *nothing* worked on React 16 until I submitted my first patch.

People that treat others trying to contribute *fixes* so poorly are why so many give up on contributing to open source projects. He's a jerk, and that's fine, I'm a jerk too and that's why I'm more willing to call him out for it and to metaphorically take my ball and go home. Lots of people are jerks in OSS, and some of them are really good at it (e.g.: Linus Torvalds). Even the good ones sometimes they need to be called jerks, hopefully so they're less so the next time. Nobody, with or without a title, gets to be above reproach and go without being called a jerk when they act like one.

**Comment by neoziro** [comment]
Regarding your gif, it is more a npm issue rather than a react-hot-loader issue. I suggest you to replace "build" script in "package.json" by:

```js
"build": "./node_modules/.bin/babel src --out-dir lib"
```

My thinking is that on Windows, current path has priority over build path.

Since Travis does not support Windows, it will be hard to add test I agree.

Again, your language is not correct, if I was owner of the project, I had banned you.

I think we should add a code of conduct similar to the [Babel one](https://github.com/babel/babel/blob/master/CODE_OF_CONDUCT.md) to this project. @AaronFriel you should read it, it is probably new for you.

**Comment by AaronFriel** [comment]
> Regarding your gif, it is more a npm issue rather than a react-hot-loader issue. I suggest you to replace "build" script in "package.json" by:

I know how to run the babel script manually, I am trying to submit a patch to make it so that no one else has to do this if they develop on Windows. The `.bin` path as far as I know is an implementation detail, and I can't recall where, but I remember reading advice that that Node scripts should not depend on them any longer.

> My thinking is that on Windows, current path has priority over build path.

🤦‍♂️

I said that in my commit.

**Comment by neoziro** [comment]
A lot of scripts are relying on "./node_modules/.bin", I prefer to rely on it rather than introducing a breaking change for every users. Also in npm scripts, we should not have to specify it, but if it is not working correctly on Windows it could be a bug in npm itself.

**Comment by neoziro** [comment]
You are probably thinking about https://github.com/npm/npm/issues/4040#issuecomment-27159695

I think it is a bug in npm itself, we can't rename our proper files because there is a conflict with npm scripts. It is a npm issue not a react-hot-loader issue.

**Comment by gaearon** [comment]
I won’t even read these comments because they’re so emotionally charged. Please stop.

I’m sorry you’re experiencing issues contributing on Windows. It hasn’t been our priority to fix them, but we’re happy to take fixes that don’t rename files. Changing public API to fix the build doesn’t make sense to me.

But again, I don’t feel like diving in to read about your issues because of the tone of your posts. Please stop attacking @neoziro and file a clear issue describing *what exactly* is broken, not what you think about us.
