### ISSUE TITLE
Hot reloading not working with connected component.

### ISSUE THREAD

**Issue by Koenkk** [gaearon/react-hot-loader#668]
### Description
Hot reloading does not work with a connected component.

### Expected behavior
It works :)

### Actual behavior
It does not work :(

### Environment

React Hot Loader version: 3.0.0

Run these commands in the project folder and fill in their results:

1. `node -v`: v8.6.0
2. `npm -v`: 5.4.2

Then, specify:

1. Operating system: Ubuntu 17.04
2. Browser and version: Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)

### Reproducible Demo
https://github.com/Koenkk/react-hot-loader-problem

**Comment by neoziro** [comment]
It is a known issue, a solution emerged in https://github.com/gaearon/react-hot-loader/issues/650#issuecomment-336156450.

**Comment by Koenkk** [comment]
That issue is about >= 2 levels of HoC. If I understand correctly my demo has only 1 level of HoC: https://github.com/Koenkk/react-hot-loader-problem/blob/master/app/App.js#L18

**Comment by theKashey** [comment]
@Koenkk - this is a quite complex problem. And source lays somewhere in webpack. 
So what the problem - shrinkwrap. Just delete it and it will work. Or use yarn (as long it ignores it).
More deeply - react-hot-loader will use quite old version of react-deep-force-update. Just with another interface.
That is the question for @neoziro - why `lastest` by time version is 1xx, and `lastest` by number is 2xx.

As result - you, @Koenkk, have `react-deep-force-update:*` in your package.json.
*** NEVER use wildcard import, and NEVER import things you not gonna use ****
That will install react-deep-force-update v 2xx, and react-hot-loader will install desired version as nested node modules.

Magically, it will use not `own` and correct version of deep update, but the top most one.
As result - everything will not work. Just because calling deepForceUpdate to bypass connect's PureComponent will do - __nothing__.

But this is webpack issue, as long it perform incorrect rewiring of a modules.
```js
/***/ "./node_modules/react-hot-loader/lib/AppContainer.dev.js":
/***/ (function(module, exports, __webpack_require__) {

var React = __webpack_require__("./node_modules/react/index.js"); <- points to top most React.
var PropTypes = __webpack_require__("./node_modules/prop-types/index.js");
var deepForceUpdate = __webpack_require__("./node_modules/react-deep-force-update/lib/index.js");
^^^ points to top most react-deep-force.
must be ./node_modules/react-hot-loader/node_modules/react-deep-force-update/lib/index.js
```
So, webpack just ignores './', ie `relative to the current file` and uses it's default behavior - relative to the project root


So - how to solve.

Just remove all node modules you are not going to use from package json.

**Comment by Koenkk** [comment]
This indeed solves the problem, thanks @theKashey !

For future reference, I pushed the fix to my repository: https://github.com/Koenkk/react-hot-loader-problem

**Comment by neoziro** [comment]
Nice! Thanks @theKashey and sorry for having missed the true problem @Koenkk.
