### ISSUE TITLE
Turning react-router hot loadable

### ISSUE THREAD

**Issue by edygar** [gaearon/react-hot-loader#68]
Is there a way to make `react-router` hot? I tried it a little here but couldn't achieve.

I didn't understand how `hot` works, indeed. Is there a hook to unmount and mount? What I need is to teardown the old router and run the new one.

**Comment by gaearon** [comment]
Do you mean changing the route configuration midfight? This will be possible with react-router 0.12 (not released yet) because it adds [`router.replaceRoutes`](https://github.com/rackt/react-router/commit/2ac2510e6e7f980f66e57050dc51488af012643b).

Once it's released, you'll be able to achieve this by using React Hot Loader [manual mode](https://github.com/gaearon/react-hot-loader/blob/master/docs/README.md#manual-mode-experimental) (`react-hot?manual` in Webpack config) and code like this:

```js
var routes = require('./routes'),
    Router = require('react-router');

router = Router.create({
  routes: routes,
  location: Router.HistoryLocation
});

if (module.hot) {
  module.hot.accept('./routes', function () {
    routes = require('./routes');
    router.replaceRoutes(routes);
  });
}
```

Manual mode just lets hot updates bubble up `require` hierarchy until they're handled in `router.js`.

**Comment by edygar** [comment]
Well, `react-hot?manual` should just work now with current `teardown` and recreating and running the router, shouldn't?

I did try something similar to the following and it didn't worked, It ended up with a infinite recursion and stack overflow.
```js
var routes = require('./routes'),
    renderer = require('./renderer'),
    Router = require('react-router');

function startUpRouter(routes) {
  router = Router.create({
    routes: routes,
    location: Router.HistoryLocation
  });
  router.run(renderer);
  return router;
}

if (module.hot) {
  module.hot.accept('./routes', function () {
    routes = require('./routes');
    router.teardown(); 
    startUpRouter(routes);
  });
}

startUpRouter(routes)
```

**Comment by gaearon** [comment]
Your approach actually works for me with 0.11.6.

**Comment by edygar** [comment]
I couldn't verify yet, because of this problem: https://github.com/gaearon/react-hot-loader/issues/77

**Comment by edygar** [comment]
Verified. The approach actually works, the RangeError was caused because another issue https://github.com/gaearon/react-hot-loader/issues/77 . 

=) Hot Routers gave me a nice productivity boost
