### ISSUE TITLE
code from README.md not corretly

### ISSUE THREAD

**Issue by joy-yu** [gaearon/react-hot-loader#691]
#### just see the comment
from Getting started
4. Wrap your application into <AppContainer>, all children of <AppContainer> will be reloaded when a change occurs:
``` javascript
// main.js
import React from 'react'
import ReactDOM from 'react-dom'
import { AppContainer } from 'react-hot-loader'
import App from './containers/App'

const render = Component => {
  ReactDOM.render(
    <AppContainer>
      <Component />
    </AppContainer>,
    document.getElementById('root'),
  )
}

render(App)

// Webpack Hot Module Replacement API
if (module.hot) {
  module.hot.accept('./containers/App', () => { render(App) })  // fail hot update!
  // module.hot.accept(App, () => { render(App) })  // It should be this!
}
```

**Comment by adipascu** [comment]
Hi @joy-yu 
From the [documentation](https://webpack.github.io/docs/hot-module-replacement.html#accept) I see that module.hot.accept requires a string as the first parameter.
I think the readme example is correct.

**Comment by joy-yu** [comment]
@adipascu I have created a repository [here](https://github.com/joy-yu/antd-template) 
Note the code at src/main.js line 28. React hot load now is invalid.

**Comment by adipascu** [comment]
@joy-yu You are not using the api as designed but it is still working. 
I noticed that the documentation from https://webpack.js.org/api/hot-module-replacement/#accept is a bit different than the source code. If the first parameter is a function, it accepts the current module (main.js in your case).
Try replacing the call with `module.hot.accept(() => { })`, you can notice that it still works.
I am not sure what is the underlying issue here. Try to make a smaller [sscce](http://sscce.org/) that is easier to check and debug.

**Comment by joy-yu** [comment]
@adipascu Thank you for your explanation.I didn't do enough research about the `accept` api before.
And I create a new simple repo [here](https://github.com/joy-yu/exp). It just refer to the readme.md and the hot load is still invalid.
