### ISSUE TITLE
Next version: v4

### ISSUE THREAD

**Issue by neoziro** [gaearon/react-hot-loader#707]
This issue is designed to centralize discussions about the next version of React Hot Loader.

### Documentation

- [x] Update react-deep-force-update README
- [x] Update react-hot-loader README
- [x] Update react-stand-in README
- [x] Update main README
- [x] Add changelog for v4
- [x] Update troubleshooting

### Tests

- [x] Add a sanbox environment to test real use-cases
- [x] Add code coverage (codecov)

### Chore

- [x] Add a release scripts to automate release 

### Breaking changes

- [x] Remove webpack plugin

**Comment by theKashey** [comment]
Ok. I’ll take a look. 
I am also trying to solve the last issue about state loss in #703. 
Look like we could repeat and even improve behaviour of v1 (#643)

**Comment by theKashey** [comment]
@neoziro - this is ok, that `modern` tests are failing. The classes in the tests does not `REGENERATE_METHOD`, injected by babel plugin. As result they could not reproduce arrow functions.

**Comment by neoziro** [comment]
@theKashey we have to solve it I think

**Comment by neoziro** [comment]
I think we are now stable on lerna branch. We should add a sandbox projet to be able to test real use-cases and then we could release a beta.

Also would be great to work on a detailed changelog about what's new in v4 and the trade-offs.

**Comment by theKashey** [comment]
So, I could bring back 15/16 boilerplates as sandboxes. And please add one new point - remove webpack plugin.

**Comment by theKashey** [comment]
One more thing to be updated - troubleshooting.

**Comment by theKashey** [comment]
One more thing to be added (and discussed) - `HotExportedComponent`.
```js
 //index.js
 const App = loadable(() => import('./App'))
  
 //App.js
 export default hotExported(module, Component)
```
As long popular loaders, like loadable-components or react-loadable, does not, and from point of view - should not, support ReactHotLoader flow, we might provide a better solution.

V3 allows code change to bubble to the top, and then expects the code to be reinitialized from top to bottom. But loaders will not re-require async components on the fly, and code branches behind them will be kept old. 

V1 had a different behaviour putting module.accept automagically in all the places. That was a quite bad behaviour, and long it has no brains.

Using the helper function user can call HOC in the `right` place with component and module variable. Next RHL can setup module self-acceptance and wrap component with AppContainer to rerender it when the time comes.
The same can be archived for the top level components. Instead of adding
```js
module.hot.accept('./containers/App', () => { render(App) })
```
to the Application level, one can wrap App export with `hotExported` and magic might happen - code will be propertly updated on HRM event. And this is much more delcaration.

And this is actually 3 lines-long function, which already exists in V1 code base, and which might save a lot of time and make life easier.

**Comment by neoziro** [comment]
@theKashey I like the idea of reducing and improving boilerplate and if we can make it work with code splitting it is a great news!

**Comment by theKashey** [comment]
And the main - accomplish all the things before xmass.

**Comment by theKashey** [comment]
All major tasks resolved. Imo - it's time to release a beta.

**Comment by neoziro** [comment]
Yes I think so, I will try to do it before xmass.

**Comment by theKashey** [comment]
That was a plan 🎅 🎄 🎁

**Comment by neoziro** [comment]
Release as beta: https://github.com/gaearon/react-hot-loader/tree/next
