### ISSUE TITLE
Component not reloaded

### ISSUE THREAD

**Issue by James2516** [gaearon/react-hot-loader#712]
https://github.com/James2516/hot-reload
I'm trying to add hot loader to an existing webpack project.

![](https://i.imgur.com/yoB6QPr.png)

It detected file changes but did not reload the component.

To reproduce:
1. `yarn && yarn start`
2. change `src/App.js` content

**Comment by jljorgenson18** [comment]
Looking at your webpack config, it looks like you are configuring babel there and it is not picking up the configuration in babelrc. Because of that, the hot reloader babel plugin is most likely not getting picked up. I would remove the query for the babel rule and consider using the env option in the babelrc to target the correct babel configuration (https://babeljs.io/docs/usage/babelrc/#env-option)

**Comment by neoziro** [comment]
The problem is that your Babel config is not correct, you don't include "react-hot-loader/babel". https://github.com/James2516/hot-reload/blob/master/config/webpack/Base.js

If I can give you an advice, use only one simple webpack.config.js with some ternaries. An example : https://github.com/smooth-code/website/blob/master/webpack.config.babel.js
