### ISSUE TITLE
Leverage AST for diffing modules

### ISSUE THREAD

**Issue by NeekSandhu** [gaearon/react-hot-loader#714]
## Problem#1

At the moment `RHL` will not preserve variable `count` in example below:

```javascript
import { Component } from 'react';
let count = 0;
export class AppHeader extends Component {
 /** impl */
}
```
## Proposal

1. Use a good `AST` generator to get `AST` of the initial module
2. Extract names (`identifiers`) of all top level variables
3. Wrap them in something like:
```javascript
__REACT_HOT_LOADER__.topLevelDeclares[moduleId] = {
    count: count
};
```
4. Inject the above snip somewhere in the module during transpilation.
5. When user saves the file, remove declarations of same identifier and assign them value from loaded module.
6. Win

**Comment by theKashey** [comment]
It's may sound a bit strange, but I never think about preserving values of local-global variables. Maybe cos I don't have any?
As long this transformation is required for ALL files - it does not worth it. Very heavy magic.

But, anyway, it should be a part of Webpack's HotModuleReplacement flow, not React-hot-loader. Please, crosspost your issue to webpack repo. And they have to have some cooking receipts for this case, cos it is so common.

PS: could be done by module self-accept and marking count as export, so you can copy-parse old values to the new ones. Ugly - yep. Working - yes.

**Comment by NeekSandhu** [comment]
Well AFAIK the goal is to deliver the best developer experience ever, the end user that is.

With that in mind, I'd prefer as a user myself, to not have to manually tinker with the tooling to get it "working".

And again, I would be more than happy to send a PR (proof of concept) if this gets a green light.

**Comment by theKashey** [comment]
As I can see - this may introduce more bugs, than solve.
If you are going to copy over only Plain Old Objects? Only non-constants? Does it enough? What about second level variables? IIFEs are around. What if you will use you `count` as key in some lookup table? Will you copy over that table? It is a object, it may be a function, why not to copy over React Component? But you will override your change...

If you are able to write a clear, and straightforward spec - go for it. I couldn't.

Anyway - this should be separated from RHL, just because this is a different thing. If one day, someone will create a more ideal HMR. And not only React customers will be happy, but also VueJs and Angular ones.

Until then we all have just to maintain a bit better code. You could just extract this variable to a separate module, and it will keep its value. Already to simply.

**Comment by theKashey** [comment]
V4 makes this proposal obsolete.
