### ISSUE TITLE
How do I unit test hot loader behavior in my app?

### ISSUE THREAD

**Issue by TrevorBurnham** [gaearon/react-hot-loader#896]
I'd like to make test assertions for my app's RHL behavior, e.g. "If `ComponentA` is replaced by `ComponentB`, then I expect `ComponentB` to have this state." However, I don't see any API for doing so. RHL's internal tests [use a `register()` method](https://github.com/gaearon/react-hot-loader/blob/9ef4c35aa62695c46fdbca6929de1db77ad22ba2/test/AppContainer.dev.test.js#L26) for this purpose, which doesn't appear to be exported [in the dev build](https://github.com/gaearon/react-hot-loader/blob/9ef4c35aa62695c46fdbca6929de1db77ad22ba2/src/index.dev.js).

Is there an approach that I'm overlooking?

**Comment by theKashey** [comment]
```js
export default ReactHotLoader
```
and then 
```js
reactHotLoader.register(type, NAME, FILENAME);
```

But why do you need to test it? I will not recommend to have RHL enabled in testing environment due 2 points:
 - it does not make sence
 - it actually breaking Jest(#872) and Enzyme(#897)

**Comment by TrevorBurnham** [comment]
So, I have a use case that looks like this:

```jsx
class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {thing: props.defaultThing};
  }

  componentWillMount() {
    this._transformedThing = transform(this.state.thing);
  }

  componentWillUpdate(nextProps, nextState) {
    this._transformedThing = transform(nextState.thing);
  }
}
```

I want a test case in my app to confirm that, if I make changes to `MyComponent` in a dev environment where RHL is in use, then the instance variable will reflect the preserved state. Something along the lines of:

```jsx
import { shallow } from 'enzyme';

const wrapper = shallow(<MyComponent defaultThing="foo" />);
expect(wrapper.instance()._transformedThing).toEqual(transform("foo"));
wrapper.setState({thing: "bar"});
expect(wrapper.instance()._transformedThing).toEqual(transform("bar"));
// Now simulate MyComponent being replaced by RHL with a new component
// with the same implementation...
expect(hotReplacedWrapper.state("thing")).toBe("bar");
expect(hotReplacedWrapper.instance()._transformedThing).toEqual(transform("bar"));
```

Unfortunately, I can't think of any way to simulate a component instance's state being altered between the execution of its `constructor()` and `componentWillMount()`, as RHL does.

**Comment by theKashey** [comment]
why not to add your case to RHL's own tests?

**Comment by TrevorBurnham** [comment]
I was hoping to have a test such that, when I upgrade my project's dependencies (e.g. bumping `react` or `react-hot-loader` to the latest version), it would confirm that my component will still behave as expected when hot-replaced. I realize that it's a little esoteric for a project to have test coverage for dev-mode behavior, but I'd worry otherwise that the dev-mode behavior might change.

I'd feel less of a need for such a test if the react-hot-loader documentation were more explicit about how it preserves state in terms of the component lifecycle. Please tell me if this is an accurate description:

> When `ComponentA` is replaced by `ComponentB`, the following occurs:
> 1. All `ComponentA` instances are unmounted (`componentWillUnmount()`)
> 2. A `ComponentB` instance is created for each unmounted `ComponentA` instance (`constructor()`)
> 3. The `state` from each `ComponentA` instance is transferred to its corresponding `ComponentB` replacement
> 4. All `ComponentB` instances are mounted (`componentWillMount()`)

**Comment by theKashey** [comment]
When ComponentA is replaced by ComponentB, the following occurs:

 - All ComponentA instances are __NOT__ unmounted (componentWillUnmount())
 - A ComponentB instance is created, and ComponentA instnce is created (constructor())
 - All variables unchanged between a new ComponentA instance and existing ComponentA instances, are replaced by ComponentB variables.
 - As result the state got unchanged.
 - All arrow function or _bound_ members, as long they are variables, is replaced and updated.
 - ComponentA prototype is replaced by ComponentB prototype. As result ComponentA does not exists anymore.
 - All ComponentB instances are NOT mounted (componentWillMount()), as long they were not unmounted.

As result
 - hot update went seamlessly
 - constructor of ComponentA was called once
 - constructor of ComponentB was called once
 - render method of ComponentA instance might be called at least twice.
 - no lifecycle method was called.

That was actually a thing to discuss - we are detecting changes in lifecycle methods, and displaying a warning about it. We are not executing them due to "no time travel" rule. Aka component already exists, we and wont change its past.
It is possible to not to update these components, but unmount them in real. Changes in lifecycle methods are rare, but applying that changes - it might be something user could expect.

**Comment by TrevorBurnham** [comment]
Ah, I see. Thanks, that's a useful clarification. Somehow I'd been under the impression that react-hot-loader was unmounting the changed components and mounting their replacements.
