### ISSUE TITLE
Connection Refused Errors

### ISSUE THREAD

**Issue by alexhancock** [gaearon/react-hot-loader#91]
Often times I get connection refused errors when it tries to load the hot update JSON responses.

`GET ....hot-update.json net::ERR_CONNECTION_REFUSED`

I can't seem to identify anything concrete that causes this - it just seems to happen sometimes and not others.

When it works, it works great. Keep up the good work on the loader!

**Comment by gaearon** [comment]
I think I have this after long sessions in debugger. There must be a timeout or something. Is this your case?

**Comment by alexhancock** [comment]
It doesn't seem to only happen when I have had a long session in the debugger.

Sometimes I will go for a while and hot reload will continue to work. Other times, I will come from a fresh pageload of my web app, and then the first time I make a code change which should trigger a hot update, this will happen.

**Comment by gaearon** [comment]
Weird. If you find a way to reliably reproduce this, let me know!

**Comment by alexhancock** [comment]
Will do. Thanks!

**Comment by jnsandrew** [comment]
I'm having the same problem and found this open ticket - I can also reliably get it to do this. It's basically the only thing it does. Attached a screenshot of my console: 

![screen shot 2015-07-03 at 14 57 37](https://cloud.githubusercontent.com/assets/455002/8500421/e6bd6456-2193-11e5-8f6f-2491f0a9c1a8.png)

My site runs on port :3000 while webpack-dev-server runs on :3001. If I try and access the refused URL on another tab or through a REST app both return the json and a 200 status (on both 3000 and 3001). I'm not sure if it should  load the script on 3000 or if I've missed a config setting somewhere? My node app has a proxy setup so that it redirects everything on:

/scripts/*
/socket.io/*

to http://127.0.0.1:3001 using http-proxy package

![screen shot 2015-07-03 at 15 03 51](https://cloud.githubusercontent.com/assets/455002/8500510/c2e1fdca-2194-11e5-83cb-f258f57dbef5.png)

Not sure what else you need?

**Comment by chrisvfritz** [comment]
@alexhancock @jnsandrew Is it possible you're running into [the cross origin problem](https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#no-access-control-allow-origin-header-is-present-on-the-requested-resource)?

**Comment by jnsandrew** [comment]
I added the access control origin setting into my config just in case, but weirdly what fixed it for me was, previously I was creating a server using express:

    const app = express();

    app.listen(port, function () {
    });

But if I use the 'http' package and create a server using that, I don't get an error anymore:

    const app = express();
    ...
    var server = http.createServer(app);

    server.on('upgrade', function (req, socket, head) {
      proxy.ws(req, socket, head);
    });

    server.listen(port, function () {
      console.log('Server running on port ' + port);
    });

I got the above code from server.js in https://github.com/christianalfoni/webpack-express-boilerplate

So I just have an if, which uses 'http' in development and app.listen in production.

**Comment by gaearon** [comment]
Regardless of the origin of this problem, it's not related to React Hot Loader per se.
Please file it with Webpack Dev Server (or something else :-).
